# Site settings
author: Leah Schlackman
title: Leah's Block 
header-img: img/home-bg.png
email: leahemily1@gmail.com
copyright_name: Leah Schlackman
description: > # this means to ignore newlines until "baseurl:"
  Notes and essays from my Flatiron experience 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  LeahESc

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
